### ISSUE TITLE
Feat: Tracking the record of the violator in Khaenri'ah channel

### ISSUE THREAD

**Issue by Iqrar99** [Iqrar99/WarnetBot#57]
**Is your feature request related to a problem? Please describe.**
Some of the violators have been punished by giving them a Buronan role and also exp subtract. But there is no log to know how many times they violate the rules.

**Describe the solution you'd like**
Make a command to warn them with Khaenri'ah rules and save the record into the database.

**To-Do**

- [ ] `war!buron warn <user>`: The warning level is auto increment with max level is 4. Will do an action based on the level.
- [ ] `war!buron inc <user>`: Increase the warning level of a user.
- [ ] `war!buron dec <user>`: Decrease the warning level of a user. If the user is level 0, the user record will be removed from database.
- [ ] `war!buron list`: List of the violators.
